spring:
  application:
    name: call-hello-service
server:
  port: 0

  ribbon:
    eureka:
      enabled: true
#    listOfServers: localhost:9090,localhost:9091,localhost:9092
    ServerListRefreshInterval: 1000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    hostname: localhost
    preferIpAddress: false


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
      base-path: /actuator

---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/


#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream, info, health
#      base-path: /actuator
#      cors:
#        allowed-origins: true
#
#    health:
#      enabled: true
#      show-details: always
#    enabled-by-default: false