version: "3"
services:
  call-hello-service:
    image: call-hello-service:v1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
  config-server:
    image: config-server:v1
    ports:
      - "8888:8888"
    depends_on:
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  discovery-server:
    image: discovery-server:v1
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      placement:
        constraints: [node.role == manager]
  gateway-application:
    image: gateway-application:v1
    depends_on:
      - config-server
      - discovery-server
    ports:
      - "8765:8765"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
  first-hello-service:
    image: first-hello-service:v1
    depends_on:
      - config-server
      - discovery-server
    deploy:
      placement:
        constraints: [node.role == worker]
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 150M
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  monitor-dashboard:
    image: monitor-dashboard:v1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
    ports:
      - "7979:7979"
  second-hello-service:
    image: second-hello-service:v1
    depends_on:
      - config-server
      - discovery-server
    deploy:
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 150M
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "9875:9875"
  turbine-application:
    image: turbine-application:v1
    depends_on:
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8989:8989"
  zipkin-stream-server:
    image: zipkin-stream-server:v1
    depends_on:
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "9411:9411"
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]