#spring:
#  application:
#    name: zuul-server
#  main:
#    allow-bean-definition-overriding: true
#server:
#  port: 8762
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
#    registerWithEureka: true
#    fetchRegistry: true
#
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#    hostname: localhost
#    preferIpAddress: false
#
#

info:
  component: Edge server (based on Netflix Zuul)

spring:
  application:
    name: edge-server
  cloud:
    config:
      failFast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 5000
        maxAttempts: 20
      discovery:
        serviceId: config-server
        enabled: false
      uri: https://localhost:8761

server:
  port: 8762