spring:
  application:
    name: second-saying-hello-service
  cloud:
    config:
      failFast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 5000
        maxAttempts: 20
      discovery:
        serviceId: config-server
        enabled: false
      uri: http://localhost:8888
server:
  port: 9875

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/

  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    hostname: localhost
    preferIpAddress: false


---


spring:
  profiles: docker
  cloud:
    config:
      discovery:
        enabled: false
      uri: http://config-server:8888

eureka.instance.preferIpAddress: true
eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/