spring:
  application:
    name: turbine-application
server:
  port: 8989

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/

  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    hostname: localhost
    preferIpAddress: false

turbine:
  appConfig: call-hello-service
  clusterNameExpression: new String('default')
  instanceUrlSuffix:
    default: actuator/hystrix.stream


---
spring.profiles: docker
eureka.instance.preferIpAddress: true
eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/