spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/rfgholami/microservices-sample-config.git
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/

  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    hostname: localhost
    preferIpAddress: false


